proto:
  - data: ["position","username","email","gender","popularity"]
  - types: [1,8,8,4,2]

4beb: ["1","gdabbs0","kbase0@bbb.org","F","12.34"]
cbeb: ["2","ekollaschek1","mattwool1@statcounter.com","M","11.12"]
4be6: ["3","jdingate2","csictornes2@chron.com","F","45.18"]
cbe7: ["4","doliphand3","ewestfalen3@apple.com","M","54.84"]
cbec: ["5","dkerfod4","grutty4@hud.gov","F","73.27"]
4bea: ["6","mjankovic5","rkernar5@gov.uk","F","22.72"]
cbe8: ["7","bbattison6","ofontanet6@privacy.gov.au","M","16.46"]
4be5: ["8","rberger7","ccasely7@bbc.co.uk","M","33.17"]
cbe5: ["9","tbartol8","kpickavant8@xinhuanet.com","F","51.19"]
cbea: ["10","hluxmoore9","zgentery9@europa.eu","F","56.23"]
4be8: ["11","sdisleea","nandreaccia@foxnews.com","F","1.74"]
4bed: ["12","acrowb","gtaillardb@prnewswire.com","M","98.58"]
0be4: ["13","bpoolyc","rhargreavec@alexa.com","F","44.80"]
8be2: ["14","steanbyd","cwalczynskid@webs.com","M","32.11"]
8bea: ["15","rwhelpdalee","jelmhirste@zdnet.com","M","70.98"]
0be8: ["16","ggrebertf","rouldcottf@xinhuanet.com","M","64.67"]
8be3: ["17","rsantarellig","dleppingtong@howstuffworks.com","M","88.99"]
8bec: ["18","egaytonh","fswanbourneh@flickr.com","M","28.71"]
0bea: ["19","hmunksi","lbendigi@yelp.com","F","98.88"]
8be6: ["20","eraycroftj","kkenvinj@typepad.com","F","85.48"]
0beb: ["21","ibossomk","ebrewinsk@bizjournals.com","F","53.63"]
8beb: ["22","dhallidayl","rhannaml@telegraph.co.uk","F","26.58"]
0be7: ["23","jellissm","ahunterm@dailymail.co.uk","F","72.24"]
0bec: ["24","fleneven","bfyldesn@hostgator.com","F","39.36"]
8be8: ["25","ocloneyo","msichao@prweb.com","M","27.17"]
4be7: ["26","akamingp","rbettyp@arizona.edu","F","78.12"]
cbe9: ["27","cgilliceq","nhairsnapeq@tamu.edu","F","12.33"]
4be4: ["28","jmooreedr","jfetherstonhaughr@arstechnica.com","M","93.19"]
4be9: ["29","lbaxs","esturrs@nsw.gov.au","M","17.36"]
cbe0: ["30","rnusseyt","mlehrert@mtv.com","F","37.38"]